### ISSUE TITLE
Email verification is broken

### ISSUE THREAD

**Issue by cor** [woording/woording-api#18]
I didn't get an email when i tried to create a new user

**Comment by PhiliPdB** [comment]
Google blocks the sign-in, so we need to create a noreply@woording.com email address and configure it in the api

**Comment by cor** [comment]
And where can we create noreply@woording.com ?

**Comment by PhiliPdB** [comment]
We need to create a email server

**Comment by PhiliPdB** [comment]
Reason why it doesn't work anymore...
![screenshot_2015-12-11-09-37-56](https://cloud.githubusercontent.com/assets/7051056/11739377/4363d0f2-9feb-11e5-9a00-1248ac128a79.png)

**Comment by mikevanb** [comment]
Was this corrected in https://github.com/woording/woording-api/commit/b2fc9954ae2706bd08f3fefa86746895d7c98cf3 ?

**Comment by PhiliPdB** [comment]
Yes, forgot that there was an issue :disappointed:
