### ISSUE TITLE
iCloud Keychain positioning is broken in ngDialog

### ISSUE THREAD

**Issue by cor** [woording/woording-api#6]
The position is a few spaces off vertically, this probably has something to do with the "slide in from above" effect
![screenshot](https://cloud.githubusercontent.com/assets/4728062/9832116/c382383a-5970-11e5-9b1a-761b9bf3f809.png)

**Comment by PhiliPdB** [comment]
Looks like this can't be fixed, because Safari decides where to place the keychain.

**Comment by cor** [comment]
This is related to woording-web
